name = "rsvp-wedding"
main = "build/index.js"
compatibility_date = "2024-01-15"

[[d1_databases]]
binding = "DB"
database_name = "rsvp-db"
database_id = "your-database-id-here"

[vars]
ENVIRONMENT = "production"

